<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-IT7ALNU" failures="1" tests="4" name="com.learning.selenium.SeleniumProject.AppTest" time="0.014" errors="0" timestamp="2024-12-17T11:30:08 GMT-05:00" skipped="3">
  <testcase classname="com.learning.selenium.SeleniumProject.AppTest" name="methodInterceptorRetryTest" time="0.001">
    <skipped/>
  </testcase> <!-- methodInterceptorRetryTest -->
  <system-out/>
  <testcase classname="com.learning.selenium.SeleniumProject.AppTest" name="methodInterceptorRetryTest" time="0.010">
    <skipped/>
  </testcase> <!-- methodInterceptorRetryTest -->
  <system-out/>
  <testcase classname="com.learning.selenium.SeleniumProject.AppTest" name="methodInterceptorRetryTest" time="0.002">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.learning.selenium.SeleniumProject.AppTest.methodInterceptorRetryTest(AppTest.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </failure>
  </testcase> <!-- methodInterceptorRetryTest -->
  <system-out/>
  <testcase classname="com.learning.selenium.SeleniumProject.AppTest" name="methodInterceptorRetryTest" time="0.001">
    <skipped/>
  </testcase> <!-- methodInterceptorRetryTest -->
  <system-out/>
</testsuite> <!-- com.learning.selenium.SeleniumProject.AppTest -->
